//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Placements.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Placements.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AgencyWarer.
        /// </summary>
        internal static string constAgencyWarer {
            get {
                return ResourceManager.GetString("constAgencyWarer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DepartmentECO.
        /// </summary>
        internal static string constDepartmentECO {
            get {
                return ResourceManager.GetString("constDepartmentECO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        internal static string constDistrict {
            get {
                return ResourceManager.GetString("constDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DistrictCEC.
        /// </summary>
        internal static string constDistrictCEC {
            get {
                return ResourceManager.GetString("constDistrictCEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeologicalCompany.
        /// </summary>
        internal static string constGeologicalCompany {
            get {
                return ResourceManager.GetString("constGeologicalCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeologicalService.
        /// </summary>
        internal static string constGeologicalService {
            get {
                return ResourceManager.GetString("constGeologicalService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinistryECO.
        /// </summary>
        internal static string constMinistryECO {
            get {
                return ResourceManager.GetString("constMinistryECO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlacementRegionCEC.
        /// </summary>
        internal static string constPlacementRegionCEC {
            get {
                return ResourceManager.GetString("constPlacementRegionCEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlacementsAgencyWarer.
        /// </summary>
        internal static string constPlacementsAgencyWarer {
            get {
                return ResourceManager.GetString("constPlacementsAgencyWarer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlacementsDepEco.
        /// </summary>
        internal static string constPlacementsDepEco {
            get {
                return ResourceManager.GetString("constPlacementsDepEco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlacementsDistrictCEC.
        /// </summary>
        internal static string constPlacementsDistrictCEC {
            get {
                return ResourceManager.GetString("constPlacementsDistrictCEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlacementsDSA.
        /// </summary>
        internal static string constPlacementsDSA {
            get {
                return ResourceManager.GetString("constPlacementsDSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlacementsGeologicalCompany.
        /// </summary>
        internal static string constPlacementsGeologicalCompany {
            get {
                return ResourceManager.GetString("constPlacementsGeologicalCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlacementsGeologicalService.
        /// </summary>
        internal static string constPlacementsGeologicalService {
            get {
                return ResourceManager.GetString("constPlacementsGeologicalService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlacementsMinistryECO.
        /// </summary>
        internal static string constPlacementsMinistryECO {
            get {
                return ResourceManager.GetString("constPlacementsMinistryECO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlacementsRAW.
        /// </summary>
        internal static string constPlacementsRAW {
            get {
                return ResourceManager.GetString("constPlacementsRAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlacementsRSA.
        /// </summary>
        internal static string constPlacementsRSA {
            get {
                return ResourceManager.GetString("constPlacementsRSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string constRegion {
            get {
                return ResourceManager.GetString("constRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegionAgencyWarer.
        /// </summary>
        internal static string constRegionAgencyWarer {
            get {
                return ResourceManager.GetString("constRegionAgencyWarer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegionCEC.
        /// </summary>
        internal static string constRegionCEC {
            get {
                return ResourceManager.GetString("constRegionCEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSA.
        /// </summary>
        internal static string constRSA {
            get {
                return ResourceManager.GetString("constRSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukraine.
        /// </summary>
        internal static string constUkraine {
            get {
                return ResourceManager.GetString("constUkraine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DistrictSES {
            get {
                object obj = ResourceManager.GetObject("DistrictSES", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EcologyDepartment {
            get {
                object obj = ResourceManager.GetObject("EcologyDepartment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EcologyInspections {
            get {
                object obj = ResourceManager.GetObject("EcologyInspections", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Державне Агенство Водних ресурсів України.
        /// </summary>
        internal static string FullAgencyWarer {
            get {
                return ResourceManager.GetString("FullAgencyWarer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Державна Служба Геології та Надр України.
        /// </summary>
        internal static string FullGeologicalService {
            get {
                return ResourceManager.GetString("FullGeologicalService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Міністерство Екології Та Природних Ресурсів України.
        /// </summary>
        internal static string FullMinistryECO {
            get {
                return ResourceManager.GetString("FullMinistryECO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Geological {
            get {
                object obj = ResourceManager.GetObject("Geological", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RegionAgencyWarer {
            get {
                object obj = ResourceManager.GetObject("RegionAgencyWarer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RegionSES {
            get {
                object obj = ResourceManager.GetObject("RegionSES", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДержВодАгенство України.
        /// </summary>
        internal static string ShortAgencyWarer {
            get {
                return ResourceManager.GetString("ShortAgencyWarer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Геологическая компания Украины.
        /// </summary>
        internal static string ShortGeologicalCompany {
            get {
                return ResourceManager.GetString("ShortGeologicalCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Геологічна служба України.
        /// </summary>
        internal static string ShortGeologicalService {
            get {
                return ResourceManager.GetString("ShortGeologicalService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to МінПрироди України.
        /// </summary>
        internal static string ShortMinistryECO {
            get {
                return ResourceManager.GetString("ShortMinistryECO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управління Екології.
        /// </summary>
        internal static string stringDepartmentECO {
            get {
                return ResourceManager.GetString("stringDepartmentECO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Районна СЕС.
        /// </summary>
        internal static string stringDistrictSES {
            get {
                return ResourceManager.GetString("stringDistrictSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управління водних ресурсів.
        /// </summary>
        internal static string stringRegionRAW {
            get {
                return ResourceManager.GetString("stringRegionRAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обласна СЕС.
        /// </summary>
        internal static string stringRegionSES {
            get {
                return ResourceManager.GetString("stringRegionSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Украина.
        /// </summary>
        internal static string stringUkraine {
            get {
                return ResourceManager.GetString("stringUkraine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ukraine {
            get {
                object obj = ResourceManager.GetObject("Ukraine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UkraineMain {
            get {
                object obj = ResourceManager.GetObject("UkraineMain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string xmlAddress {
            get {
                return ResourceManager.GetString("xmlAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building.
        /// </summary>
        internal static string xmlBuilding {
            get {
                return ResourceManager.GetString("xmlBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;&lt;Address&gt;&lt;Index /&gt;&lt;Region /&gt;&lt;District /&gt;&lt;SettlementType /&gt;&lt;SettlementName /&gt;&lt;ToponimType /&gt;&lt;ToponimName /&gt;&lt;Building /&gt;&lt;Corpus /&gt;&lt;OfficeType /&gt;&lt;OfficeName /&gt;&lt;/Address&gt;.
        /// </summary>
        internal static string xmlConstAddress {
            get {
                return ResourceManager.GetString("xmlConstAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;&lt;FullName&gt;&lt;FirstName /&gt;&lt;ParentName /&gt;&lt;LastName /&gt;&lt;/FullName&gt;.
        /// </summary>
        internal static string xmlConstName {
            get {
                return ResourceManager.GetString("xmlConstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corpus.
        /// </summary>
        internal static string xmlCorpus {
            get {
                return ResourceManager.GetString("xmlCorpus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        internal static string xmlDistrict {
            get {
                return ResourceManager.GetString("xmlDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName.
        /// </summary>
        internal static string xmlFirstName {
            get {
                return ResourceManager.GetString("xmlFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName.
        /// </summary>
        internal static string xmlFullName {
            get {
                return ResourceManager.GetString("xmlFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        internal static string xmlIndex {
            get {
                return ResourceManager.GetString("xmlIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName.
        /// </summary>
        internal static string xmlLastName {
            get {
                return ResourceManager.GetString("xmlLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfficeName.
        /// </summary>
        internal static string xmlOfficeName {
            get {
                return ResourceManager.GetString("xmlOfficeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfficeType.
        /// </summary>
        internal static string xmlOfficeType {
            get {
                return ResourceManager.GetString("xmlOfficeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParentName.
        /// </summary>
        internal static string xmlParentName {
            get {
                return ResourceManager.GetString("xmlParentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string xmlRegion {
            get {
                return ResourceManager.GetString("xmlRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SettlementName.
        /// </summary>
        internal static string xmlSettlementName {
            get {
                return ResourceManager.GetString("xmlSettlementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SettlementType.
        /// </summary>
        internal static string xmlSettlementType {
            get {
                return ResourceManager.GetString("xmlSettlementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToponimName.
        /// </summary>
        internal static string xmlToponimName {
            get {
                return ResourceManager.GetString("xmlToponimName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToponimType.
        /// </summary>
        internal static string xmlToponimType {
            get {
                return ResourceManager.GetString("xmlToponimType", resourceCulture);
            }
        }
    }
}
