//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Placements.db {
    using System;
    using System.Collections.Generic;
    using System.Collections;
    using Castle.ActiveRecord;
    
    
    [ActiveRecord()]
    public partial class tPlacementsDepEco : ActiveRecordBase<tPlacementsDepEco> {
        
        private int _iD_PlacementDepEco;
        
        private string _postDepECO;
        
        private string _shortPostDepECO;
        
        private string _postGenitiveDepECO;
        
        private string _postDativeDepECO;
        
        private string _nameDepECO;
        
        private string _nameGenitiveDepECO;
        
        private string _nameDativeDepECO;
        
        private bool _default_;
        
        private string _phone;
        
        private string _phoneMobile;
        
        private string _email_;
        
        private string _vk_com;
        
        private string _facebook;
        
        private string _twitter;
        
        private string _other;
        
        private tDepartmentECO _tDepartmentECO;
        
        [PrimaryKey(PrimaryKeyType.Native, "ID_PlacementDepEco", ColumnType="Int32")]
        public virtual int ID_PlacementDepEco {
            get {
                return this._iD_PlacementDepEco;
            }
            set {
                this._iD_PlacementDepEco = value;
            }
        }
        
        [Property("PostDepECO", ColumnType="String")]
        public virtual string PostDepECO {
            get {
                return this._postDepECO;
            }
            set {
                this._postDepECO = value;
            }
        }
        
        [Property("ShortPostDepECO", ColumnType="String")]
        public virtual string ShortPostDepECO {
            get {
                return this._shortPostDepECO;
            }
            set {
                this._shortPostDepECO = value;
            }
        }
        
        [Property("PostGenitiveDepECO", ColumnType="String")]
        public virtual string PostGenitiveDepECO {
            get {
                return this._postGenitiveDepECO;
            }
            set {
                this._postGenitiveDepECO = value;
            }
        }
        
        [Property("PostDativeDepECO", ColumnType="String")]
        public virtual string PostDativeDepECO {
            get {
                return this._postDativeDepECO;
            }
            set {
                this._postDativeDepECO = value;
            }
        }
        
        [Property("NameDepECO", ColumnType="String")]
        public virtual string NameDepECO {
            get {
                return this._nameDepECO;
            }
            set {
                this._nameDepECO = value;
            }
        }
        
        [Property("NameGenitiveDepECO", ColumnType="String")]
        public virtual string NameGenitiveDepECO {
            get {
                return this._nameGenitiveDepECO;
            }
            set {
                this._nameGenitiveDepECO = value;
            }
        }
        
        [Property("NameDativeDepECO", ColumnType="String")]
        public virtual string NameDativeDepECO {
            get {
                return this._nameDativeDepECO;
            }
            set {
                this._nameDativeDepECO = value;
            }
        }
        
        [Property("Default_", ColumnType="Boolean")]
        public virtual bool Default_ {
            get {
                return this._default_;
            }
            set {
                this._default_ = value;
            }
        }
        
        [Property("Phone", ColumnType="String")]
        public virtual string Phone {
            get {
                return this._phone;
            }
            set {
                this._phone = value;
            }
        }
        
        [Property("PhoneMobile", ColumnType="String")]
        public virtual string PhoneMobile {
            get {
                return this._phoneMobile;
            }
            set {
                this._phoneMobile = value;
            }
        }
        
        [Property("Email_", ColumnType="String")]
        public virtual string Email_ {
            get {
                return this._email_;
            }
            set {
                this._email_ = value;
            }
        }
        
        [Property("vk_com", ColumnType="String")]
        public virtual string vk_com {
            get {
                return this._vk_com;
            }
            set {
                this._vk_com = value;
            }
        }
        
        [Property("facebook", ColumnType="String")]
        public virtual string facebook {
            get {
                return this._facebook;
            }
            set {
                this._facebook = value;
            }
        }
        
        [Property("twitter", ColumnType="String")]
        public virtual string twitter {
            get {
                return this._twitter;
            }
            set {
                this._twitter = value;
            }
        }
        
        [Property("Other", ColumnType="String")]
        public virtual string Other {
            get {
                return this._other;
            }
            set {
                this._other = value;
            }
        }
        
        [BelongsTo()]
        public virtual tDepartmentECO tDepartmentECO {
            get {
                return this._tDepartmentECO;
            }
            set {
                this._tDepartmentECO = value;
            }
        }
    }
    
    [ActiveRecord()]
    public partial class tDepartmentECO : ActiveRecordBase<tDepartmentECO> {
        
        private int _iD_DepartmentECO;
        
        private string _depECO;
        
        private string _shortDepECO;
        
        private string _adresDepECO;
        
        private string _siteDepECO;
        
        private string _vk_com;
        
        private string _facebook;
        
        private string _twitter;
        
        private string _other;
        
        private byte[] _icon_;
        
        private string _phone;
        
        private IList<tPlacementsDepEco> _tPlacementsDepEcoes;
        
        private tRegion _tRegion;
        
        [PrimaryKey(PrimaryKeyType.Native, "ID_DepartmentECO", ColumnType="Int32")]
        public virtual int ID_DepartmentECO {
            get {
                return this._iD_DepartmentECO;
            }
            set {
                this._iD_DepartmentECO = value;
            }
        }
        
        [Property("DepECO", ColumnType="String")]
        public virtual string DepECO {
            get {
                return this._depECO;
            }
            set {
                this._depECO = value;
            }
        }
        
        [Property("ShortDepECO", ColumnType="String")]
        public virtual string ShortDepECO {
            get {
                return this._shortDepECO;
            }
            set {
                this._shortDepECO = value;
            }
        }
        
        [Property("AdresDepECO", ColumnType="String")]
        public virtual string AdresDepECO {
            get {
                return this._adresDepECO;
            }
            set {
                this._adresDepECO = value;
            }
        }
        
        [Property("SiteDepECO", ColumnType="String")]
        public virtual string SiteDepECO {
            get {
                return this._siteDepECO;
            }
            set {
                this._siteDepECO = value;
            }
        }
        
        [Property("vk_com", ColumnType="String")]
        public virtual string vk_com {
            get {
                return this._vk_com;
            }
            set {
                this._vk_com = value;
            }
        }
        
        [Property("facebook", ColumnType="String")]
        public virtual string facebook {
            get {
                return this._facebook;
            }
            set {
                this._facebook = value;
            }
        }
        
        [Property("twitter", ColumnType="String")]
        public virtual string twitter {
            get {
                return this._twitter;
            }
            set {
                this._twitter = value;
            }
        }
        
        [Property("Other", ColumnType="String")]
        public virtual string Other {
            get {
                return this._other;
            }
            set {
                this._other = value;
            }
        }
        
        [Property("icon_", ColumnType="BinaryBlob")]
        public virtual byte[] icon_ {
            get {
                return this._icon_;
            }
            set {
                this._icon_ = value;
            }
        }
        
        [Property("Phone", ColumnType="String")]
        public virtual string Phone {
            get {
                return this._phone;
            }
            set {
                this._phone = value;
            }
        }
        
        [HasMany(typeof(tPlacementsDepEco), ColumnKey="tDepartmentECO")]
        public virtual IList<tPlacementsDepEco> tPlacementsDepEcoes {
            get {
                return this._tPlacementsDepEcoes;
            }
            set {
                this._tPlacementsDepEcoes = value;
            }
        }
        
        [OneToOne()]
        public virtual tRegion tRegion {
            get {
                return this._tRegion;
            }
            set {
                this._tRegion = value;
            }
        }
    }
    
    [ActiveRecord()]
    public partial class tPlacementRegionCEC : ActiveRecordBase<tPlacementRegionCEC> {
        
        private int _iD_PlacementRegionCEC;
        
        private string _postRegionCEC;
        
        private string _shortPostRegionCEC;
        
        private string _postGenitiveRegionCEC;
        
        private string _postDativeRegionCEC;
        
        private string _nameRegionCEC;
        
        private string _nameGenitiveRegionCEC;
        
        private string _nameDativeRegionCEC;
        
        private bool _default_;
        
        private string _phone;
        
        private string _phoneMobile;
        
        private string _email_;
        
        private string _vk_com;
        
        private string _facebook;
        
        private string _twitter;
        
        private string _other;
        
        private tRegionCEC _tRegionCEC;
        
        [PrimaryKey(PrimaryKeyType.Native, "ID_PlacementRegionCEC", ColumnType="Int32")]
        public virtual int ID_PlacementRegionCEC {
            get {
                return this._iD_PlacementRegionCEC;
            }
            set {
                this._iD_PlacementRegionCEC = value;
            }
        }
        
        [Property("PostRegionCEC", ColumnType="String")]
        public virtual string PostRegionCEC {
            get {
                return this._postRegionCEC;
            }
            set {
                this._postRegionCEC = value;
            }
        }
        
        [Property("ShortPostRegionCEC", ColumnType="String")]
        public virtual string ShortPostRegionCEC {
            get {
                return this._shortPostRegionCEC;
            }
            set {
                this._shortPostRegionCEC = value;
            }
        }
        
        [Property("PostGenitiveRegionCEC", ColumnType="String")]
        public virtual string PostGenitiveRegionCEC {
            get {
                return this._postGenitiveRegionCEC;
            }
            set {
                this._postGenitiveRegionCEC = value;
            }
        }
        
        [Property("PostDativeRegionCEC", ColumnType="String")]
        public virtual string PostDativeRegionCEC {
            get {
                return this._postDativeRegionCEC;
            }
            set {
                this._postDativeRegionCEC = value;
            }
        }
        
        [Property("NameRegionCEC", ColumnType="String")]
        public virtual string NameRegionCEC {
            get {
                return this._nameRegionCEC;
            }
            set {
                this._nameRegionCEC = value;
            }
        }
        
        [Property("NameGenitiveRegionCEC", ColumnType="String")]
        public virtual string NameGenitiveRegionCEC {
            get {
                return this._nameGenitiveRegionCEC;
            }
            set {
                this._nameGenitiveRegionCEC = value;
            }
        }
        
        [Property("NameDativeRegionCEC", ColumnType="String")]
        public virtual string NameDativeRegionCEC {
            get {
                return this._nameDativeRegionCEC;
            }
            set {
                this._nameDativeRegionCEC = value;
            }
        }
        
        [Property("Default_", ColumnType="Boolean")]
        public virtual bool Default_ {
            get {
                return this._default_;
            }
            set {
                this._default_ = value;
            }
        }
        
        [Property("Phone", ColumnType="String")]
        public virtual string Phone {
            get {
                return this._phone;
            }
            set {
                this._phone = value;
            }
        }
        
        [Property("PhoneMobile", ColumnType="String")]
        public virtual string PhoneMobile {
            get {
                return this._phoneMobile;
            }
            set {
                this._phoneMobile = value;
            }
        }
        
        [Property("Email_", ColumnType="String")]
        public virtual string Email_ {
            get {
                return this._email_;
            }
            set {
                this._email_ = value;
            }
        }
        
        [Property("vk_com", ColumnType="String")]
        public virtual string vk_com {
            get {
                return this._vk_com;
            }
            set {
                this._vk_com = value;
            }
        }
        
        [Property("facebook", ColumnType="String")]
        public virtual string facebook {
            get {
                return this._facebook;
            }
            set {
                this._facebook = value;
            }
        }
        
        [Property("twitter", ColumnType="String")]
        public virtual string twitter {
            get {
                return this._twitter;
            }
            set {
                this._twitter = value;
            }
        }
        
        [Property("Other", ColumnType="String")]
        public virtual string Other {
            get {
                return this._other;
            }
            set {
                this._other = value;
            }
        }
        
        [BelongsTo()]
        public virtual tRegionCEC tRegionCEC {
            get {
                return this._tRegionCEC;
            }
            set {
                this._tRegionCEC = value;
            }
        }
    }
    
    [ActiveRecord()]
    public partial class tRegionCEC : ActiveRecordBase<tRegionCEC> {
        
        private int _iD_RegionCEC;
        
        private string _regionCEC;
        
        private string _shortRegionCEC;
        
        private string _adresRegionCEC;
        
        private string _siteRegionCEC;
        
        private string _vk_com;
        
        private string _facebook;
        
        private string _twitter;
        
        private string _other;
        
        private byte[] _icon_;
        
        private string _phone;
        
        private IList<tPlacementRegionCEC> _tPlacementRegionCECs;
        
        private tRegion _tRegion;
        
        [PrimaryKey(PrimaryKeyType.Native, "ID_RegionCEC", ColumnType="Int32")]
        public virtual int ID_RegionCEC {
            get {
                return this._iD_RegionCEC;
            }
            set {
                this._iD_RegionCEC = value;
            }
        }
        
        [Property("RegionCEC", ColumnType="String")]
        public virtual string RegionCEC {
            get {
                return this._regionCEC;
            }
            set {
                this._regionCEC = value;
            }
        }
        
        [Property("ShortRegionCEC", ColumnType="String")]
        public virtual string ShortRegionCEC {
            get {
                return this._shortRegionCEC;
            }
            set {
                this._shortRegionCEC = value;
            }
        }
        
        [Property("AdresRegionCEC", ColumnType="String")]
        public virtual string AdresRegionCEC {
            get {
                return this._adresRegionCEC;
            }
            set {
                this._adresRegionCEC = value;
            }
        }
        
        [Property("SiteRegionCEC", ColumnType="String")]
        public virtual string SiteRegionCEC {
            get {
                return this._siteRegionCEC;
            }
            set {
                this._siteRegionCEC = value;
            }
        }
        
        [Property("vk_com", ColumnType="String")]
        public virtual string vk_com {
            get {
                return this._vk_com;
            }
            set {
                this._vk_com = value;
            }
        }
        
        [Property("facebook", ColumnType="String")]
        public virtual string facebook {
            get {
                return this._facebook;
            }
            set {
                this._facebook = value;
            }
        }
        
        [Property("twitter", ColumnType="String")]
        public virtual string twitter {
            get {
                return this._twitter;
            }
            set {
                this._twitter = value;
            }
        }
        
        [Property("Other", ColumnType="String")]
        public virtual string Other {
            get {
                return this._other;
            }
            set {
                this._other = value;
            }
        }
        
        [Property("icon_", ColumnType="BinaryBlob")]
        public virtual byte[] icon_ {
            get {
                return this._icon_;
            }
            set {
                this._icon_ = value;
            }
        }
        
        [Property("Phone", ColumnType="String")]
        public virtual string Phone {
            get {
                return this._phone;
            }
            set {
                this._phone = value;
            }
        }
        
        [HasMany(typeof(tPlacementRegionCEC), ColumnKey="tRegionCEC")]
        public virtual IList<tPlacementRegionCEC> tPlacementRegionCECs {
            get {
                return this._tPlacementRegionCECs;
            }
            set {
                this._tPlacementRegionCECs = value;
            }
        }
        
        [OneToOne()]
        public virtual tRegion tRegion {
            get {
                return this._tRegion;
            }
            set {
                this._tRegion = value;
            }
        }
    }
    
    [ActiveRecord()]
    public partial class tPlacementsRegionAgencyWarer : ActiveRecordBase<tPlacementsRegionAgencyWarer> {
        
        private int _iD_PlacementsRAW;
        
        private string _postRAW;
        
        private string _shortPostRAW;
        
        private string _postGenitiveRAW;
        
        private string _postDativeRAW;
        
        private string _nameRAW;
        
        private string _nameGenitiveRAW;
        
        private string _nameDativeRAW;
        
        private bool _default_;
        
        private string _phone;
        
        private string _phoneMobile;
        
        private string _email_;
        
        private string _vk_com;
        
        private string _facebook;
        
        private string _twitter;
        
        private string _other;
        
        private tRegionAgencyWarer _tRegionAgencyWarer;
        
        [PrimaryKey(PrimaryKeyType.Native, "ID_PlacementsRAW", ColumnType="Int32")]
        public virtual int ID_PlacementsRAW {
            get {
                return this._iD_PlacementsRAW;
            }
            set {
                this._iD_PlacementsRAW = value;
            }
        }
        
        [Property("PostRAW", ColumnType="String")]
        public virtual string PostRAW {
            get {
                return this._postRAW;
            }
            set {
                this._postRAW = value;
            }
        }
        
        [Property("ShortPostRAW", ColumnType="String")]
        public virtual string ShortPostRAW {
            get {
                return this._shortPostRAW;
            }
            set {
                this._shortPostRAW = value;
            }
        }
        
        [Property("PostGenitiveRAW", ColumnType="String")]
        public virtual string PostGenitiveRAW {
            get {
                return this._postGenitiveRAW;
            }
            set {
                this._postGenitiveRAW = value;
            }
        }
        
        [Property("PostDativeRAW", ColumnType="String")]
        public virtual string PostDativeRAW {
            get {
                return this._postDativeRAW;
            }
            set {
                this._postDativeRAW = value;
            }
        }
        
        [Property("NameRAW", ColumnType="String")]
        public virtual string NameRAW {
            get {
                return this._nameRAW;
            }
            set {
                this._nameRAW = value;
            }
        }
        
        [Property("NameGenitiveRAW", ColumnType="String")]
        public virtual string NameGenitiveRAW {
            get {
                return this._nameGenitiveRAW;
            }
            set {
                this._nameGenitiveRAW = value;
            }
        }
        
        [Property("NameDativeRAW", ColumnType="String")]
        public virtual string NameDativeRAW {
            get {
                return this._nameDativeRAW;
            }
            set {
                this._nameDativeRAW = value;
            }
        }
        
        [Property("Default_", ColumnType="Boolean")]
        public virtual bool Default_ {
            get {
                return this._default_;
            }
            set {
                this._default_ = value;
            }
        }
        
        [Property("Phone", ColumnType="String")]
        public virtual string Phone {
            get {
                return this._phone;
            }
            set {
                this._phone = value;
            }
        }
        
        [Property("PhoneMobile", ColumnType="String")]
        public virtual string PhoneMobile {
            get {
                return this._phoneMobile;
            }
            set {
                this._phoneMobile = value;
            }
        }
        
        [Property("Email_", ColumnType="String")]
        public virtual string Email_ {
            get {
                return this._email_;
            }
            set {
                this._email_ = value;
            }
        }
        
        [Property("vk_com", ColumnType="String")]
        public virtual string vk_com {
            get {
                return this._vk_com;
            }
            set {
                this._vk_com = value;
            }
        }
        
        [Property("facebook", ColumnType="String")]
        public virtual string facebook {
            get {
                return this._facebook;
            }
            set {
                this._facebook = value;
            }
        }
        
        [Property("twitter", ColumnType="String")]
        public virtual string twitter {
            get {
                return this._twitter;
            }
            set {
                this._twitter = value;
            }
        }
        
        [Property("Other", ColumnType="String")]
        public virtual string Other {
            get {
                return this._other;
            }
            set {
                this._other = value;
            }
        }
        
        [BelongsTo()]
        public virtual tRegionAgencyWarer tRegionAgencyWarer {
            get {
                return this._tRegionAgencyWarer;
            }
            set {
                this._tRegionAgencyWarer = value;
            }
        }
    }
    
    [ActiveRecord()]
    public partial class tRegionAgencyWarer : ActiveRecordBase<tRegionAgencyWarer> {
        
        private int _iD_RAW;
        
        private string _rAW;
        
        private string _shortRAW;
        
        private string _adresRAW;
        
        private string _siteRAW;
        
        private string _vk_com;
        
        private string _facebook;
        
        private string _twitter;
        
        private string _other;
        
        private byte[] _icon_;
        
        private string _phone;
        
        private IList<tPlacementsRegionAgencyWarer> _tPlacementsRegionAgencyWarers;
        
        private tRegion _tRegion;
        
        [PrimaryKey(PrimaryKeyType.Native, "ID_RAW", ColumnType="Int32")]
        public virtual int ID_RAW {
            get {
                return this._iD_RAW;
            }
            set {
                this._iD_RAW = value;
            }
        }
        
        [Property("RAW", ColumnType="String")]
        public virtual string RAW {
            get {
                return this._rAW;
            }
            set {
                this._rAW = value;
            }
        }
        
        [Property("ShortRAW", ColumnType="String")]
        public virtual string ShortRAW {
            get {
                return this._shortRAW;
            }
            set {
                this._shortRAW = value;
            }
        }
        
        [Property("AdresRAW", ColumnType="String")]
        public virtual string AdresRAW {
            get {
                return this._adresRAW;
            }
            set {
                this._adresRAW = value;
            }
        }
        
        [Property("SiteRAW", ColumnType="String")]
        public virtual string SiteRAW {
            get {
                return this._siteRAW;
            }
            set {
                this._siteRAW = value;
            }
        }
        
        [Property("vk_com", ColumnType="String")]
        public virtual string vk_com {
            get {
                return this._vk_com;
            }
            set {
                this._vk_com = value;
            }
        }
        
        [Property("facebook", ColumnType="String")]
        public virtual string facebook {
            get {
                return this._facebook;
            }
            set {
                this._facebook = value;
            }
        }
        
        [Property("twitter", ColumnType="String")]
        public virtual string twitter {
            get {
                return this._twitter;
            }
            set {
                this._twitter = value;
            }
        }
        
        [Property("Other", ColumnType="String")]
        public virtual string Other {
            get {
                return this._other;
            }
            set {
                this._other = value;
            }
        }
        
        [Property("icon_", ColumnType="BinaryBlob")]
        public virtual byte[] icon_ {
            get {
                return this._icon_;
            }
            set {
                this._icon_ = value;
            }
        }
        
        [Property("Phone", ColumnType="String")]
        public virtual string Phone {
            get {
                return this._phone;
            }
            set {
                this._phone = value;
            }
        }
        
        [HasMany(typeof(tPlacementsRegionAgencyWarer), ColumnKey="tRegionAgencyWarer")]
        public virtual IList<tPlacementsRegionAgencyWarer> tPlacementsRegionAgencyWarers {
            get {
                return this._tPlacementsRegionAgencyWarers;
            }
            set {
                this._tPlacementsRegionAgencyWarers = value;
            }
        }
        
        [OneToOne()]
        public virtual tRegion tRegion {
            get {
                return this._tRegion;
            }
            set {
                this._tRegion = value;
            }
        }
    }
    
    [ActiveRecord()]
    public partial class tRegion : ActiveRecordBase<tRegion> {
        
        private int _iD_Region;
        
        private string _region;
        
        private string _genitiveRegion;
        
        private string _dativeRegion;
        
        private string _other;
        
        private byte[] _icon_;
        
        private IList<tDistrict> _tDistricts;
        
        private tDepartmentECO _tDepartmentECO;
        
        private tRegionCEC _tRegionCEC;
        
        private tRegionAgencyWarer _tRegionAgencyWarer;
        
        private tRegionalStateAdministration _tRegionalStateAdministration;
        
        [PrimaryKey(PrimaryKeyType.Native, "ID_Region", ColumnType="Int32")]
        public virtual int ID_Region {
            get {
                return this._iD_Region;
            }
            set {
                this._iD_Region = value;
            }
        }
        
        [Property("Region", ColumnType="String")]
        public virtual string Region {
            get {
                return this._region;
            }
            set {
                this._region = value;
            }
        }
        
        [Property("GenitiveRegion", ColumnType="String")]
        public virtual string GenitiveRegion {
            get {
                return this._genitiveRegion;
            }
            set {
                this._genitiveRegion = value;
            }
        }
        
        [Property("DativeRegion", ColumnType="String")]
        public virtual string DativeRegion {
            get {
                return this._dativeRegion;
            }
            set {
                this._dativeRegion = value;
            }
        }
        
        [Property("Other", ColumnType="String")]
        public virtual string Other {
            get {
                return this._other;
            }
            set {
                this._other = value;
            }
        }
        
        [Property("icon_", ColumnType="BinaryBlob")]
        public virtual byte[] icon_ {
            get {
                return this._icon_;
            }
            set {
                this._icon_ = value;
            }
        }
        
        [HasMany(typeof(tDistrict), ColumnKey="tRegion")]
        public virtual IList<tDistrict> tDistricts {
            get {
                return this._tDistricts;
            }
            set {
                this._tDistricts = value;
            }
        }
        
        [OneToOne()]
        public virtual tDepartmentECO tDepartmentECO {
            get {
                return this._tDepartmentECO;
            }
            set {
                this._tDepartmentECO = value;
            }
        }
        
        [OneToOne()]
        public virtual tRegionCEC tRegionCEC {
            get {
                return this._tRegionCEC;
            }
            set {
                this._tRegionCEC = value;
            }
        }
        
        [OneToOne()]
        public virtual tRegionAgencyWarer tRegionAgencyWarer {
            get {
                return this._tRegionAgencyWarer;
            }
            set {
                this._tRegionAgencyWarer = value;
            }
        }
        
        [OneToOne()]
        public virtual tRegionalStateAdministration tRegionalStateAdministration {
            get {
                return this._tRegionalStateAdministration;
            }
            set {
                this._tRegionalStateAdministration = value;
            }
        }
    }
    
    [ActiveRecord()]
    public partial class tDistrict : ActiveRecordBase<tDistrict> {
        
        private int _iD_District;
        
        private string _district;
        
        private string _genitiveDistrict;
        
        private string _dativeDistrict;
        
        private string _other;
        
        private byte[] _icon_;
        
        private tRegion _tRegion;
        
        private tDistrictCEC _tDistrictCEC;
        
        private tDistrictStateAdministration _tDistrictStateAdministration;
        
        [PrimaryKey(PrimaryKeyType.Native, "ID_District", ColumnType="Int32")]
        public virtual int ID_District {
            get {
                return this._iD_District;
            }
            set {
                this._iD_District = value;
            }
        }
        
        [Property("District", ColumnType="String")]
        public virtual string District {
            get {
                return this._district;
            }
            set {
                this._district = value;
            }
        }
        
        [Property("GenitiveDistrict", ColumnType="String")]
        public virtual string GenitiveDistrict {
            get {
                return this._genitiveDistrict;
            }
            set {
                this._genitiveDistrict = value;
            }
        }
        
        [Property("DativeDistrict", ColumnType="String")]
        public virtual string DativeDistrict {
            get {
                return this._dativeDistrict;
            }
            set {
                this._dativeDistrict = value;
            }
        }
        
        [Property("Other", ColumnType="String")]
        public virtual string Other {
            get {
                return this._other;
            }
            set {
                this._other = value;
            }
        }
        
        [Property("icon_", ColumnType="BinaryBlob")]
        public virtual byte[] icon_ {
            get {
                return this._icon_;
            }
            set {
                this._icon_ = value;
            }
        }
        
        [BelongsTo()]
        public virtual tRegion tRegion {
            get {
                return this._tRegion;
            }
            set {
                this._tRegion = value;
            }
        }
        
        [OneToOne()]
        public virtual tDistrictCEC tDistrictCEC {
            get {
                return this._tDistrictCEC;
            }
            set {
                this._tDistrictCEC = value;
            }
        }
        
        [OneToOne()]
        public virtual tDistrictStateAdministration tDistrictStateAdministration {
            get {
                return this._tDistrictStateAdministration;
            }
            set {
                this._tDistrictStateAdministration = value;
            }
        }
    }
    
    [ActiveRecord()]
    public partial class tRegionalStateAdministration : ActiveRecordBase<tRegionalStateAdministration> {
        
        private int _iD_RSA;
        
        private string _rSA;
        
        private string _shortRSA;
        
        private string _adresRSA;
        
        private string _siteRSA;
        
        private string _vk_com;
        
        private string _facebook;
        
        private string _twitter;
        
        private string _other;
        
        private byte[] _icon_;
        
        private string _phone;
        
        private IList<tPlacementsRegionalStateAdministration> _tPlacementsRegionalStateAdministrations;
        
        private tRegion _tRegion;
        
        [PrimaryKey(PrimaryKeyType.Native, "ID_RSA", ColumnType="Int32")]
        public virtual int ID_RSA {
            get {
                return this._iD_RSA;
            }
            set {
                this._iD_RSA = value;
            }
        }
        
        [Property("RSA", ColumnType="String")]
        public virtual string RSA {
            get {
                return this._rSA;
            }
            set {
                this._rSA = value;
            }
        }
        
        [Property("ShortRSA", ColumnType="String")]
        public virtual string ShortRSA {
            get {
                return this._shortRSA;
            }
            set {
                this._shortRSA = value;
            }
        }
        
        [Property("AdresRSA", ColumnType="String")]
        public virtual string AdresRSA {
            get {
                return this._adresRSA;
            }
            set {
                this._adresRSA = value;
            }
        }
        
        [Property("SiteRSA", ColumnType="String")]
        public virtual string SiteRSA {
            get {
                return this._siteRSA;
            }
            set {
                this._siteRSA = value;
            }
        }
        
        [Property("vk_com", ColumnType="String")]
        public virtual string vk_com {
            get {
                return this._vk_com;
            }
            set {
                this._vk_com = value;
            }
        }
        
        [Property("facebook", ColumnType="String")]
        public virtual string facebook {
            get {
                return this._facebook;
            }
            set {
                this._facebook = value;
            }
        }
        
        [Property("twitter", ColumnType="String")]
        public virtual string twitter {
            get {
                return this._twitter;
            }
            set {
                this._twitter = value;
            }
        }
        
        [Property("Other", ColumnType="String")]
        public virtual string Other {
            get {
                return this._other;
            }
            set {
                this._other = value;
            }
        }
        
        [Property("icon_", ColumnType="BinaryBlob")]
        public virtual byte[] icon_ {
            get {
                return this._icon_;
            }
            set {
                this._icon_ = value;
            }
        }
        
        [Property("Phone", ColumnType="String")]
        public virtual string Phone {
            get {
                return this._phone;
            }
            set {
                this._phone = value;
            }
        }
        
        [HasMany(typeof(tPlacementsRegionalStateAdministration), ColumnKey="tRegionalStateAdministration")]
        public virtual IList<tPlacementsRegionalStateAdministration> tPlacementsRegionalStateAdministrations {
            get {
                return this._tPlacementsRegionalStateAdministrations;
            }
            set {
                this._tPlacementsRegionalStateAdministrations = value;
            }
        }
        
        [OneToOne()]
        public virtual tRegion tRegion {
            get {
                return this._tRegion;
            }
            set {
                this._tRegion = value;
            }
        }
    }
    
    [ActiveRecord()]
    public partial class tPlacementsRegionalStateAdministration : ActiveRecordBase<tPlacementsRegionalStateAdministration> {
        
        private int _iD_PlacementsRSA;
        
        private string _postRSA;
        
        private string _shortPostRSA;
        
        private string _postGenitiveRSA;
        
        private string _postDativeRSA;
        
        private string _nameRSA;
        
        private string _nameGenitiveRSA;
        
        private string _nameDativeRSA;
        
        private bool _default_;
        
        private string _phone;
        
        private string _phoneMobile;
        
        private string _email_;
        
        private string _vk_com;
        
        private string _facebook;
        
        private string _twitter;
        
        private string _other;
        
        private tRegionalStateAdministration _tRegionalStateAdministration;
        
        [PrimaryKey(PrimaryKeyType.Native, "ID_PlacementsRSA", ColumnType="Int32")]
        public virtual int ID_PlacementsRSA {
            get {
                return this._iD_PlacementsRSA;
            }
            set {
                this._iD_PlacementsRSA = value;
            }
        }
        
        [Property("PostRSA", ColumnType="String")]
        public virtual string PostRSA {
            get {
                return this._postRSA;
            }
            set {
                this._postRSA = value;
            }
        }
        
        [Property("ShortPostRSA", ColumnType="String")]
        public virtual string ShortPostRSA {
            get {
                return this._shortPostRSA;
            }
            set {
                this._shortPostRSA = value;
            }
        }
        
        [Property("PostGenitiveRSA", ColumnType="String")]
        public virtual string PostGenitiveRSA {
            get {
                return this._postGenitiveRSA;
            }
            set {
                this._postGenitiveRSA = value;
            }
        }
        
        [Property("PostDativeRSA", ColumnType="String")]
        public virtual string PostDativeRSA {
            get {
                return this._postDativeRSA;
            }
            set {
                this._postDativeRSA = value;
            }
        }
        
        [Property("NameRSA", ColumnType="String")]
        public virtual string NameRSA {
            get {
                return this._nameRSA;
            }
            set {
                this._nameRSA = value;
            }
        }
        
        [Property("NameGenitiveRSA", ColumnType="String")]
        public virtual string NameGenitiveRSA {
            get {
                return this._nameGenitiveRSA;
            }
            set {
                this._nameGenitiveRSA = value;
            }
        }
        
        [Property("NameDativeRSA", ColumnType="String")]
        public virtual string NameDativeRSA {
            get {
                return this._nameDativeRSA;
            }
            set {
                this._nameDativeRSA = value;
            }
        }
        
        [Property("Default_", ColumnType="Boolean")]
        public virtual bool Default_ {
            get {
                return this._default_;
            }
            set {
                this._default_ = value;
            }
        }
        
        [Property("Phone", ColumnType="String")]
        public virtual string Phone {
            get {
                return this._phone;
            }
            set {
                this._phone = value;
            }
        }
        
        [Property("PhoneMobile", ColumnType="String")]
        public virtual string PhoneMobile {
            get {
                return this._phoneMobile;
            }
            set {
                this._phoneMobile = value;
            }
        }
        
        [Property("Email_", ColumnType="String")]
        public virtual string Email_ {
            get {
                return this._email_;
            }
            set {
                this._email_ = value;
            }
        }
        
        [Property("vk_com", ColumnType="String")]
        public virtual string vk_com {
            get {
                return this._vk_com;
            }
            set {
                this._vk_com = value;
            }
        }
        
        [Property("facebook", ColumnType="String")]
        public virtual string facebook {
            get {
                return this._facebook;
            }
            set {
                this._facebook = value;
            }
        }
        
        [Property("twitter", ColumnType="String")]
        public virtual string twitter {
            get {
                return this._twitter;
            }
            set {
                this._twitter = value;
            }
        }
        
        [Property("Other", ColumnType="String")]
        public virtual string Other {
            get {
                return this._other;
            }
            set {
                this._other = value;
            }
        }
        
        [BelongsTo()]
        public virtual tRegionalStateAdministration tRegionalStateAdministration {
            get {
                return this._tRegionalStateAdministration;
            }
            set {
                this._tRegionalStateAdministration = value;
            }
        }
    }
    
    [ActiveRecord()]
    public partial class tDistrictCEC : ActiveRecordBase<tDistrictCEC> {
        
        private int _iD_DistrictCEC;
        
        private string _districtCEC;
        
        private string _shortDistrictCEC;
        
        private string _adresDistrictCEC;
        
        private string _siteDistrictCEC;
        
        private string _vk_com;
        
        private string _facebook;
        
        private string _twitter;
        
        private string _other;
        
        private byte[] _icon_;
        
        private string _phone;
        
        private IList<tPlacementsDistrictCEC> _tPlacementsDistrictCECs;
        
        private tDistrict _tDistrict;
        
        [PrimaryKey(PrimaryKeyType.Native, "ID_DistrictCEC", ColumnType="Int32")]
        public virtual int ID_DistrictCEC {
            get {
                return this._iD_DistrictCEC;
            }
            set {
                this._iD_DistrictCEC = value;
            }
        }
        
        [Property("DistrictCEC", ColumnType="String")]
        public virtual string DistrictCEC {
            get {
                return this._districtCEC;
            }
            set {
                this._districtCEC = value;
            }
        }
        
        [Property("ShortDistrictCEC", ColumnType="String")]
        public virtual string ShortDistrictCEC {
            get {
                return this._shortDistrictCEC;
            }
            set {
                this._shortDistrictCEC = value;
            }
        }
        
        [Property("AdresDistrictCEC", ColumnType="String")]
        public virtual string AdresDistrictCEC {
            get {
                return this._adresDistrictCEC;
            }
            set {
                this._adresDistrictCEC = value;
            }
        }
        
        [Property("SiteDistrictCEC", ColumnType="String")]
        public virtual string SiteDistrictCEC {
            get {
                return this._siteDistrictCEC;
            }
            set {
                this._siteDistrictCEC = value;
            }
        }
        
        [Property("vk_com", ColumnType="String")]
        public virtual string vk_com {
            get {
                return this._vk_com;
            }
            set {
                this._vk_com = value;
            }
        }
        
        [Property("facebook", ColumnType="String")]
        public virtual string facebook {
            get {
                return this._facebook;
            }
            set {
                this._facebook = value;
            }
        }
        
        [Property("twitter", ColumnType="String")]
        public virtual string twitter {
            get {
                return this._twitter;
            }
            set {
                this._twitter = value;
            }
        }
        
        [Property("Other", ColumnType="String")]
        public virtual string Other {
            get {
                return this._other;
            }
            set {
                this._other = value;
            }
        }
        
        [Property("icon_", ColumnType="BinaryBlob")]
        public virtual byte[] icon_ {
            get {
                return this._icon_;
            }
            set {
                this._icon_ = value;
            }
        }
        
        [Property("Phone", ColumnType="String")]
        public virtual string Phone {
            get {
                return this._phone;
            }
            set {
                this._phone = value;
            }
        }
        
        [HasMany(typeof(tPlacementsDistrictCEC), ColumnKey="tDistrictCEC")]
        public virtual IList<tPlacementsDistrictCEC> tPlacementsDistrictCECs {
            get {
                return this._tPlacementsDistrictCECs;
            }
            set {
                this._tPlacementsDistrictCECs = value;
            }
        }
        
        [OneToOne()]
        public virtual tDistrict tDistrict {
            get {
                return this._tDistrict;
            }
            set {
                this._tDistrict = value;
            }
        }
    }
    
    [ActiveRecord()]
    public partial class tPlacementsDistrictCEC : ActiveRecordBase<tPlacementsDistrictCEC> {
        
        private int _iD_PlacementsDistrictCEC;
        
        private string _postDistrictCEC;
        
        private string _shorDistrictCEC;
        
        private string _postGenitiveDistrictCEC;
        
        private string _postDativeDistrictCEC;
        
        private string _nameDistrictCEC;
        
        private string _nameGenitiveDistrictCEC;
        
        private string _nameDativeDistrictCEC;
        
        private bool _default_;
        
        private string _phone;
        
        private string _phoneMobile;
        
        private string _email_;
        
        private string _vk_com;
        
        private string _facebook;
        
        private string _twitter;
        
        private string _other;
        
        private tDistrictCEC _tDistrictCEC;
        
        [PrimaryKey(PrimaryKeyType.Native, "ID_PlacementsDistrictCEC", ColumnType="Int32")]
        public virtual int ID_PlacementsDistrictCEC {
            get {
                return this._iD_PlacementsDistrictCEC;
            }
            set {
                this._iD_PlacementsDistrictCEC = value;
            }
        }
        
        [Property("PostDistrictCEC", ColumnType="String")]
        public virtual string PostDistrictCEC {
            get {
                return this._postDistrictCEC;
            }
            set {
                this._postDistrictCEC = value;
            }
        }
        
        [Property("ShorDistrictCEC", ColumnType="String")]
        public virtual string ShorDistrictCEC {
            get {
                return this._shorDistrictCEC;
            }
            set {
                this._shorDistrictCEC = value;
            }
        }
        
        [Property("PostGenitiveDistrictCEC", ColumnType="String")]
        public virtual string PostGenitiveDistrictCEC {
            get {
                return this._postGenitiveDistrictCEC;
            }
            set {
                this._postGenitiveDistrictCEC = value;
            }
        }
        
        [Property("PostDativeDistrictCEC", ColumnType="String")]
        public virtual string PostDativeDistrictCEC {
            get {
                return this._postDativeDistrictCEC;
            }
            set {
                this._postDativeDistrictCEC = value;
            }
        }
        
        [Property("NameDistrictCEC", ColumnType="String")]
        public virtual string NameDistrictCEC {
            get {
                return this._nameDistrictCEC;
            }
            set {
                this._nameDistrictCEC = value;
            }
        }
        
        [Property("NameGenitiveDistrictCEC", ColumnType="String")]
        public virtual string NameGenitiveDistrictCEC {
            get {
                return this._nameGenitiveDistrictCEC;
            }
            set {
                this._nameGenitiveDistrictCEC = value;
            }
        }
        
        [Property("NameDativeDistrictCEC", ColumnType="String")]
        public virtual string NameDativeDistrictCEC {
            get {
                return this._nameDativeDistrictCEC;
            }
            set {
                this._nameDativeDistrictCEC = value;
            }
        }
        
        [Property("Default_", ColumnType="Boolean")]
        public virtual bool Default_ {
            get {
                return this._default_;
            }
            set {
                this._default_ = value;
            }
        }
        
        [Property("Phone", ColumnType="String")]
        public virtual string Phone {
            get {
                return this._phone;
            }
            set {
                this._phone = value;
            }
        }
        
        [Property("PhoneMobile", ColumnType="String")]
        public virtual string PhoneMobile {
            get {
                return this._phoneMobile;
            }
            set {
                this._phoneMobile = value;
            }
        }
        
        [Property("Email_", ColumnType="String")]
        public virtual string Email_ {
            get {
                return this._email_;
            }
            set {
                this._email_ = value;
            }
        }
        
        [Property("vk_com", ColumnType="String")]
        public virtual string vk_com {
            get {
                return this._vk_com;
            }
            set {
                this._vk_com = value;
            }
        }
        
        [Property("facebook", ColumnType="String")]
        public virtual string facebook {
            get {
                return this._facebook;
            }
            set {
                this._facebook = value;
            }
        }
        
        [Property("twitter", ColumnType="String")]
        public virtual string twitter {
            get {
                return this._twitter;
            }
            set {
                this._twitter = value;
            }
        }
        
        [Property("Other", ColumnType="String")]
        public virtual string Other {
            get {
                return this._other;
            }
            set {
                this._other = value;
            }
        }
        
        [BelongsTo()]
        public virtual tDistrictCEC tDistrictCEC {
            get {
                return this._tDistrictCEC;
            }
            set {
                this._tDistrictCEC = value;
            }
        }
    }
    
    [ActiveRecord()]
    public partial class tDistrictStateAdministration : ActiveRecordBase<tDistrictStateAdministration> {
        
        private int _iD_DSA;
        
        private string _dSA;
        
        private string _shortDSA;
        
        private string _adresDSA;
        
        private string _siteDSA;
        
        private string _vk_com;
        
        private string _facebook;
        
        private string _twitter;
        
        private string _other;
        
        private byte[] _icon_;
        
        private string _phone;
        
        private IList<tPlacementsDistrictStateAdministration> _tPlacementsDistrictStateAdministrations;
        
        private tDistrict _tDistrict;
        
        [PrimaryKey(PrimaryKeyType.Native, "ID_DSA", ColumnType="Int32")]
        public virtual int ID_DSA {
            get {
                return this._iD_DSA;
            }
            set {
                this._iD_DSA = value;
            }
        }
        
        [Property("DSA", ColumnType="String")]
        public virtual string DSA {
            get {
                return this._dSA;
            }
            set {
                this._dSA = value;
            }
        }
        
        [Property("ShortDSA", ColumnType="String")]
        public virtual string ShortDSA {
            get {
                return this._shortDSA;
            }
            set {
                this._shortDSA = value;
            }
        }
        
        [Property("AdresDSA", ColumnType="String")]
        public virtual string AdresDSA {
            get {
                return this._adresDSA;
            }
            set {
                this._adresDSA = value;
            }
        }
        
        [Property("SiteDSA", ColumnType="String")]
        public virtual string SiteDSA {
            get {
                return this._siteDSA;
            }
            set {
                this._siteDSA = value;
            }
        }
        
        [Property("vk_com", ColumnType="String")]
        public virtual string vk_com {
            get {
                return this._vk_com;
            }
            set {
                this._vk_com = value;
            }
        }
        
        [Property("facebook", ColumnType="String")]
        public virtual string facebook {
            get {
                return this._facebook;
            }
            set {
                this._facebook = value;
            }
        }
        
        [Property("twitter", ColumnType="String")]
        public virtual string twitter {
            get {
                return this._twitter;
            }
            set {
                this._twitter = value;
            }
        }
        
        [Property("Other", ColumnType="String")]
        public virtual string Other {
            get {
                return this._other;
            }
            set {
                this._other = value;
            }
        }
        
        [Property("icon_", ColumnType="BinaryBlob")]
        public virtual byte[] icon_ {
            get {
                return this._icon_;
            }
            set {
                this._icon_ = value;
            }
        }
        
        [Property("Phone", ColumnType="String")]
        public virtual string Phone {
            get {
                return this._phone;
            }
            set {
                this._phone = value;
            }
        }
        
        [HasMany(typeof(tPlacementsDistrictStateAdministration), ColumnKey="tDistrictStateAdministration")]
        public virtual IList<tPlacementsDistrictStateAdministration> tPlacementsDistrictStateAdministrations {
            get {
                return this._tPlacementsDistrictStateAdministrations;
            }
            set {
                this._tPlacementsDistrictStateAdministrations = value;
            }
        }
        
        [OneToOne()]
        public virtual tDistrict tDistrict {
            get {
                return this._tDistrict;
            }
            set {
                this._tDistrict = value;
            }
        }
    }
    
    [ActiveRecord()]
    public partial class tPlacementsDistrictStateAdministration : ActiveRecordBase<tPlacementsDistrictStateAdministration> {
        
        private int _iD_PlacementsDSA;
        
        private string _postDSA;
        
        private string _shortPostDSA;
        
        private string _postGenitiveDSA;
        
        private string _postDativeDSA;
        
        private string _nameDSA;
        
        private string _nameGenitiveDSA;
        
        private string _nameDativeDSA;
        
        private bool _default_;
        
        private string _phone;
        
        private string _phoneMobile;
        
        private string _email_;
        
        private string _vk_com;
        
        private string _facebook;
        
        private string _twitter;
        
        private string _other;
        
        private tDistrictStateAdministration _tDistrictStateAdministration;
        
        [PrimaryKey(PrimaryKeyType.Native, "ID_PlacementsDSA", ColumnType="Int32")]
        public virtual int ID_PlacementsDSA {
            get {
                return this._iD_PlacementsDSA;
            }
            set {
                this._iD_PlacementsDSA = value;
            }
        }
        
        [Property("PostDSA", ColumnType="String")]
        public virtual string PostDSA {
            get {
                return this._postDSA;
            }
            set {
                this._postDSA = value;
            }
        }
        
        [Property("ShortPostDSA", ColumnType="String")]
        public virtual string ShortPostDSA {
            get {
                return this._shortPostDSA;
            }
            set {
                this._shortPostDSA = value;
            }
        }
        
        [Property("PostGenitiveDSA", ColumnType="String")]
        public virtual string PostGenitiveDSA {
            get {
                return this._postGenitiveDSA;
            }
            set {
                this._postGenitiveDSA = value;
            }
        }
        
        [Property("PostDativeDSA", ColumnType="String")]
        public virtual string PostDativeDSA {
            get {
                return this._postDativeDSA;
            }
            set {
                this._postDativeDSA = value;
            }
        }
        
        [Property("NameDSA", ColumnType="String")]
        public virtual string NameDSA {
            get {
                return this._nameDSA;
            }
            set {
                this._nameDSA = value;
            }
        }
        
        [Property("NameGenitiveDSA", ColumnType="String")]
        public virtual string NameGenitiveDSA {
            get {
                return this._nameGenitiveDSA;
            }
            set {
                this._nameGenitiveDSA = value;
            }
        }
        
        [Property("NameDativeDSA", ColumnType="String")]
        public virtual string NameDativeDSA {
            get {
                return this._nameDativeDSA;
            }
            set {
                this._nameDativeDSA = value;
            }
        }
        
        [Property("Default_", ColumnType="Boolean")]
        public virtual bool Default_ {
            get {
                return this._default_;
            }
            set {
                this._default_ = value;
            }
        }
        
        [Property("Phone", ColumnType="String")]
        public virtual string Phone {
            get {
                return this._phone;
            }
            set {
                this._phone = value;
            }
        }
        
        [Property("PhoneMobile", ColumnType="String")]
        public virtual string PhoneMobile {
            get {
                return this._phoneMobile;
            }
            set {
                this._phoneMobile = value;
            }
        }
        
        [Property("Email_", ColumnType="String")]
        public virtual string Email_ {
            get {
                return this._email_;
            }
            set {
                this._email_ = value;
            }
        }
        
        [Property("vk_com", ColumnType="String")]
        public virtual string vk_com {
            get {
                return this._vk_com;
            }
            set {
                this._vk_com = value;
            }
        }
        
        [Property("facebook", ColumnType="String")]
        public virtual string facebook {
            get {
                return this._facebook;
            }
            set {
                this._facebook = value;
            }
        }
        
        [Property("twitter", ColumnType="String")]
        public virtual string twitter {
            get {
                return this._twitter;
            }
            set {
                this._twitter = value;
            }
        }
        
        [Property("Other", ColumnType="String")]
        public virtual string Other {
            get {
                return this._other;
            }
            set {
                this._other = value;
            }
        }
        
        [BelongsTo()]
        public virtual tDistrictStateAdministration tDistrictStateAdministration {
            get {
                return this._tDistrictStateAdministration;
            }
            set {
                this._tDistrictStateAdministration = value;
            }
        }
    }
    
    public class dbPlacemansHelper {
        
        public static Type[] GetTypes() {
            return new Type[] {
                    typeof(tPlacementsDepEco),
                    typeof(tDepartmentECO),
                    typeof(tPlacementRegionCEC),
                    typeof(tRegionCEC),
                    typeof(tPlacementsRegionAgencyWarer),
                    typeof(tRegionAgencyWarer),
                    typeof(tRegion),
                    typeof(tDistrict),
                    typeof(tRegionalStateAdministration),
                    typeof(tPlacementsRegionalStateAdministration),
                    typeof(tDistrictCEC),
                    typeof(tPlacementsDistrictCEC),
                    typeof(tDistrictStateAdministration),
                    typeof(tPlacementsDistrictStateAdministration)};
        }
    }
}
